"""
SQL Injection Detection API — Main Application
===============================================
A FastAPI service wrapping the trained Linear SVM model.
Exposes three endpoints:

    GET  /health              — liveness check
    POST /detect              — classify a single query string
    POST /detect/batch        — classify multiple queries in one call
    POST /scan                — extract + classify all params from
                                a raw HTTP request

Run locally:
    uvicorn api.app:app --reload --host 0.0.0.0 --port 8000

Run in production:
    uvicorn api.app:app --host 0.0.0.0 --port 8000 --workers 4

Interactive docs (auto-generated by FastAPI):
    http://localhost:8000/docs      ← Swagger UI
    http://localhost:8000/redoc     ← ReDoc

⚠  CLASS IMBALANCE & THRESHOLD REMINDER
    Default threshold is 0.35 — tuned for production traffic (99%+ benign).
    Override per-request via the 'threshold' field in the request body.
    Monitor your false positive rate after deployment and adjust accordingly.
    See evaluate.py Step 6b for how to re-derive the threshold from your data.
"""

import logging
import time
from contextlib import asynccontextmanager

from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import JSONResponse

from api.schema import (
    SingleQueryRequest,
    BatchQueryRequest,
    ScanRequestParams,
    DetectionResult,
    BatchDetectionResult,
    ParamScanResult,
    HealthResponse,
)
from api.middleware import extract_params, scan_params
from src.predict    import load_pipeline, predict, predict_batch

# ── Logging ───────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
)
logger = logging.getLogger("sqli_detector.api")


# ── App lifecycle — load model once at startup ────────────────────────────────
pipeline: dict = {}

@asynccontextmanager
async def lifespan(app: FastAPI):
    """Load the model pipeline once when the server starts."""
    logger.info("Loading model pipeline...")
    pipeline.update(load_pipeline())
    logger.info(f"Model ready: {type(pipeline['model']).__name__}")
    logger.info(f"Vectorizer ready: vocab size = {len(pipeline['vectorizer'].vocabulary_):,}")
    yield
    logger.info("Shutting down.")


# ── App definition ────────────────────────────────────────────────────────────
app = FastAPI(
    title="SQL Injection Detection API",
    description=(
        "Classifies SQL query strings as **Benign** or **SQLi** using a "
        "Linear SVM trained on 98K labelled queries.\n\n"
        "⚠ **Threshold note:** The default threshold (0.35) is tuned for "
        "production traffic where 99%+ of requests are benign. "
        "Lower = more sensitive, higher = fewer false alarms."
    ),
    version="1.0.0",
    lifespan=lifespan,
)


# ── Request timing middleware ─────────────────────────────────────────────────
@app.middleware("http")
async def add_process_time_header(request: Request, call_next):
    start    = time.perf_counter()
    response = await call_next(request)
    elapsed  = (time.perf_counter() - start) * 1000
    response.headers["X-Process-Time-Ms"] = f"{elapsed:.2f}"
    return response


# ─────────────────────────────────────────────────────────────────────────────
# ENDPOINT 1 — Health check
# ─────────────────────────────────────────────────────────────────────────────
@app.get(
    "/health",
    response_model=HealthResponse,
    summary="Liveness check",
    tags=["System"],
)
def health():
    """
    Returns 200 if the model is loaded and ready to serve predictions.
    Use this for load-balancer health checks and container readiness probes.
    """
    if not pipeline:
        raise HTTPException(status_code=503, detail="Model not loaded yet.")
    return HealthResponse(
        status="ok",
        model=type(pipeline["model"]).__name__,
        threshold=0.35,
        version="1.0.0",
    )


# ─────────────────────────────────────────────────────────────────────────────
# ENDPOINT 2 — Detect (single query)
# ─────────────────────────────────────────────────────────────────────────────
@app.post(
    "/detect",
    response_model=DetectionResult,
    summary="Classify a single query string",
    tags=["Detection"],
)
def detect(req: SingleQueryRequest):
    """
    Classify one raw query string as **Benign** or **SQLi**.

    Call this from your web app for each user-supplied parameter
    before executing any database query.

    - **query**: raw string value (URL param, form field, JSON value, etc.)
    - **threshold**: override the default 0.35 if needed

    Returns full prediction including confidence score and risk level.
    """
    if not pipeline:
        raise HTTPException(status_code=503, detail="Model not loaded.")

    result = predict(req.query, pipeline, threshold=req.threshold)
    logger.info(
        f"detect | prediction={result['prediction']} | "
        f"confidence={result['confidence']} | risk={result['risk_level']}"
    )
    return DetectionResult(**result)


# ─────────────────────────────────────────────────────────────────────────────
# ENDPOINT 3 — Detect batch
# ─────────────────────────────────────────────────────────────────────────────
@app.post(
    "/detect/batch",
    response_model=BatchDetectionResult,
    summary="Classify multiple query strings in one call",
    tags=["Detection"],
)
def detect_batch(req: BatchQueryRequest):
    """
    Classify a list of query strings in a single model pass.
    More efficient than calling **/detect** in a loop for large batches.

    Use this for:
    - Log file scanning (bulk replay of historical requests)
    - Pre-flight checks before batch DB operations
    - Testing and evaluation pipelines

    ⚠ **Production note:** For real-time request scanning,
    prefer **/scan** (extracts params automatically) or **/detect**
    per-parameter. Batch is best for offline / async workloads.
    """
    if not pipeline:
        raise HTTPException(status_code=503, detail="Model not loaded.")

    df = predict_batch(req.queries, pipeline, threshold=req.threshold)

    results = [
        DetectionResult(
            query=row["query"],
            cleaned=row["cleaned"],
            label=int(row["label"]),
            prediction=row["prediction"],
            confidence=row["confidence"],
            threshold=row["threshold"],
            risk_level=row["risk_level"],
        )
        for _, row in df.iterrows()
    ]

    sqli_count  = int((df["label"] == 1).sum())
    benign_count = len(df) - sqli_count

    logger.info(
        f"detect_batch | total={len(df)} | sqli={sqli_count} | "
        f"benign={benign_count} | rate={sqli_count/len(df):.2%}"
    )

    # ⚠  Class imbalance runtime warning
    sqli_rate = sqli_count / len(df)
    if sqli_rate > 0.20:
        logger.warning(
            f"⚠  Unusually high SQLi rate: {sqli_rate:.1%}. "
            f"If this is live traffic, consider raising the threshold."
        )

    return BatchDetectionResult(
        total=len(df),
        sqli_count=sqli_count,
        benign_count=benign_count,
        sqli_rate=round(sqli_rate, 4),
        results=results,
    )


# ─────────────────────────────────────────────────────────────────────────────
# ENDPOINT 4 — Scan (full HTTP request)
# ─────────────────────────────────────────────────────────────────────────────
@app.post(
    "/scan",
    response_model=ParamScanResult,
    summary="Extract and scan all parameters from an HTTP request",
    tags=["Detection"],
)
def scan(req: ScanRequestParams):
    """
    The **primary integration endpoint** for web applications.

    Extracts every user-supplied value from a raw HTTP request —
    URL query params, POST form fields, JSON body fields, and
    relevant headers — and scans each one individually.

    If **any** parameter is flagged as SQLi, `blocked` is `True`
    and your application should reject the request with HTTP 403.

    **Typical integration:**
    ```python
    # In your web app's request handler (before any DB query)
    response = requests.post("http://localhost:8000/scan", json={
        "url":       request.url,
        "form_data": dict(request.form),
        "json_body": request.get_json(),
        "headers":   dict(request.headers),
        "threshold": 0.35,
    })
    scan_result = response.json()
    if scan_result["blocked"]:
        abort(403)
    ```

    **Parameters scanned:**
    - URL query string values (`?id=1&q=foo`)
    - POST form fields
    - JSON body values (nested dicts are flattened)
    - High-risk headers: User-Agent, Referer, X-Forwarded-For, Origin
    """
    if not pipeline:
        raise HTTPException(status_code=503, detail="Model not loaded.")

    params = extract_params(
        url=req.url,
        form_data=req.form_data,
        json_body=req.json_body,
        headers=req.headers,
    )

    if not params:
        return ParamScanResult(
            blocked=False,
            sqli_params=[],
            total_params=0,
            results=[],
        )

    scan_result = scan_params(params, pipeline, threshold=req.threshold)

    logger.info(
        f"scan | total_params={scan_result['total_params']} | "
        f"blocked={scan_result['blocked']} | "
        f"flagged={scan_result['sqli_params']}"
    )

    return ParamScanResult(**scan_result)


# ─────────────────────────────────────────────────────────────────────────────
# Global error handler — never leak internal details to the client
# ─────────────────────────────────────────────────────────────────────────────
@app.exception_handler(Exception)
async def global_exception_handler(request: Request, exc: Exception):
    logger.error(f"Unhandled error: {exc}", exc_info=True)
    return JSONResponse(
        status_code=500,
        content={"error": "Internal server error", "detail": str(exc)},
    )